Repository dnd-side-project/dnd-13th-7-frontend, pull requests merged in 2025-08, with the labels that each got.

#14 chore: 개발 환경 초기 설정(css, lint 등)
  .example.env
  .github/DISCUSSION_TEMPLATE/Issue.yml
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  .github/workflows/pull-request.yml
  .husky/commit-msg
  .husky/pre-commit
  .nvmrc
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  README.md
  commitlint.config.js
  components.json
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/instrumentation-client.ts
  src/instrumentation.ts
  src/lib/utils.ts
  src/shared/errors/SentryNetworkError.ts
  src/shared/utils/safeFetch.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/test/sample.test.ts
  tsconfig.json
  vitest.config.ts
  vitest.shims.d.ts
Labels: ⚙️ Setting

#18 style: tailwindv4에 기반한 스타일 정의 조정
  .vscode/settings.json
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/colors.css
  src/styles/colors.ts
  src/styles/fonts.css
  src/styles/globals.css
  src/styles/typography.css
  tailwind.config.ts
Labels: 🎨 Style, 🟨 중

#27 chore: msw 환경 구성
  .example.env
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/app/msw/page.tsx
  src/app/msw/ssr/page.tsx
  src/mocks/browser.ts
  src/mocks/handlers/club.ts
  src/mocks/handlers/index.ts
  src/mocks/mockServer.ts
  src/shared/providers/msw-provider.tsx
Labels: 🟩 하, ⚙️ Setting

#25 feat: 버튼 컴포넌트 작성
  src/components/atoms/button.stories.tsx
  src/components/atoms/button.tsx
  src/styles/design-tokens.css
  src/styles/typography.css
Labels: ✨ Feature, 🟨 중

#39 feat: 로그인 및 회원가입 페이지 레이아웃 작성
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/(auth)/login/page.tsx
  src/app/(root)/(routes)/(auth)/logout/page.tsx
  src/app/(root)/(routes)/(auth)/signup/hooks/useSignupForm.ts
  src/app/(root)/(routes)/(auth)/signup/page.tsx
  src/app/(root)/(routes)/layout.tsx
  src/app/page.tsx
  src/assets/icons/agree-check-icon.svg
  src/assets/icons/agree-uncheck-icon.svg
  src/assets/icons/google-icon.svg
  src/assets/icons/index.ts
  src/assets/icons/invalid-icon.svg
  src/assets/icons/kakao-icon.svg
  src/assets/images/index.ts
  src/assets/images/moyeoit-logo.svg
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Label/Label.tsx
  src/components/atoms/Label/index.ts
  src/components/atoms/Select/Select.tsx
  src/components/atoms/Select/index.ts
  src/components/atoms/checkItem/CheckItem.tsx
  src/components/molecules/Form/Form.tsx
  src/components/molecules/Form/index.ts
  src/components/molecules/layout/Header.tsx
  src/features/user/types.ts
  src/shared/configs/appValidation.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/design-tokens.css
  src/styles/globals.css
Labels: ✨ Feature, 🟨 중

#42 fix: check item 보여지는 개수 1개로 수정
  src/components/molecules/multiDropDown/MultiDropDown.tsx
Labels: 🐞 BugFix

#60 feat: API 주소 추가
  src/shared/utils/axios.ts
Labels: 🟥 상, ⚙️ Setting

#80 feat: 리뷰 작성 API 연결
  src/components/molecules/layout/Header.tsx
  src/components/molecules/layout/MobileHeader.tsx
  src/components/pages/review/new/forms/ActivityPremiumForm.tsx
  src/components/pages/review/new/forms/InterviewPremiumForm.tsx
  src/components/pages/review/new/forms/PaperPremiumForm.tsx
  src/components/pages/review/new/forms/hooks/useActivityNormalForm.ts
  src/components/pages/review/new/forms/hooks/useActivityPremiumForm.ts
  src/components/pages/review/new/forms/hooks/useInterviewNormalForm.ts
  src/components/pages/review/new/forms/hooks/useInterviewPremiumForm.ts
  src/components/pages/review/new/forms/hooks/usePaperNormalForm.ts
  src/components/pages/review/new/forms/hooks/usePaperPremiumForm.ts
  src/features/file/api.ts
  src/features/file/index.ts
  src/features/file/keys.ts
  src/features/file/mutations.ts
  src/features/file/types.ts
  src/shared/providers/auth-provider.tsx
Labels: ✨ Feature, 🟨 중

#87 feat: 준비중, 에러 페이지 추가
  public/images/construction.png
  public/images/sorry.png
  src/app/(root)/(routes)/review/explore/page.tsx
  src/app/(root)/(routes)/review/new/[kind]/[type]/page.tsx
  src/app/error.tsx
  src/components/pages/common/ConstructionPage.tsx
  src/components/pages/common/index.ts
Labels: 🟩 하, ✨ Feature

#89 feat: 마이페이지 정보 및 프로필 설정
  next.config.ts
  src/app/(root)/(routes)/(auth)/mypage/page.tsx
  src/components/molecules/layout/Header.tsx
  src/features/user/api.ts
  src/features/user/index.ts
  src/features/user/keys.ts
  src/features/user/mutations.ts
  src/features/user/queries.ts
  src/features/user/types.ts
Labels: ✨ Feature, 🟨 중

#101 feat: 좋아요 API 명세 추가
  src/features/clubs/queries.factory.ts
  src/features/like/api.ts
  src/features/like/hooks/useLike.ts
  src/features/like/index.ts
  src/features/like/keys.ts
  src/features/like/mutations.ts
  src/features/like/types.ts
Labels: ✨ Feature, 🟨 중

#103 fix: 질문 ID 통일
  src/components/pages/review/new/forms/hooks/useActivityNormalForm.ts
  src/components/pages/review/new/forms/hooks/useActivityPremiumForm.ts
  src/components/pages/review/new/forms/hooks/useInterviewNormalForm.ts
  src/components/pages/review/new/forms/hooks/useInterviewPremiumForm.ts
  src/components/pages/review/new/forms/hooks/usePaperNormalForm.ts
  src/components/pages/review/new/forms/hooks/usePaperPremiumForm.ts
  src/features/clubs/queries.factory.ts
Labels: ✨ Feature, 🟨 중
